# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Java/jdk-25

# Mod Properties
mod_version = 1.2.4-26.3
maven_group = net.dialingspoon
archives_name = multicount
enabled_platforms = fabric,neoforge

# Minecraft Properties
minecraft_version = 26.3

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.160.5+26.3
neoforge_version = 26.3.0.1-beta
